### ISSUE TITLE
c++ 接口提取特征

### ISSUE THREAD

**Issue by kingvision** [zhubuntu/MXNet-Learning-Note#2]
您好：
        非常感谢您分享的这些笔记，对我理解mxnet有很大帮助。请问，我要提取中间层特征，该怎么做呢？有c++接口吗？
谢谢

**Comment by zhubuntu** [comment]
这个中间层特征提取已经在程序中实现了，https://github.com/zhubuntu/MXNet-Learning-Note/tree/master/cpp，可以先看Readme里面有给出源程序地址，我在源程序基础上加了中间层特征输出．

**Comment by zhubuntu** [comment]
由于采用了 https://github.com/dmlc/MXNet.cpp 的新接口，旧接口对应的C++提取中间特征值的程序在新接口中我没用到就没有写，想用的话可以参考旧接口程序https://github.com/zhubuntu/MXNet-Learning-Note/tree/master/cpp/old
