### ISSUE TITLE
CNN R package

### ISSUE THREAD

**Issue by luoruisichuan** [zhubuntu/MXNet-Learning-Note#3]
你好！
请问有关于用MXNET实现CNN的R语言资料吗？
我看到有用MXNET中R的神经网络实现MNIST的例子，但不是CNN，请问你用过吗？谢谢

**Comment by luoruisichuan** [comment]
请教，有没有关于以下代码的相关说明文档？比如，
Symbol conv1 = Convolution("conv1", data, conv1_w, conv1_b, Shape(5, 5), 6);         中各个参数的意思。
Symbol data = Symbol::Variable("data");
        Symbol data_label = Symbol::Variable("data_label");
        Symbol conv1_w = Symbol::Variable("conv1_w");
        Symbol conv1_b = Symbol::Variable("conv1_b");
        Symbol fc1_w = Symbol::Variable("fc1_w");
        Symbol fc1_b = Symbol::Variable("fc1_b");
        Symbol fc2_w = Symbol::Variable("fc2_w");
        Symbol fc2_b = Symbol::Variable("fc2_b");

        Symbol conv1 =
            Convolution("conv1", data, conv1_w, conv1_b, Shape(5, 5), 6);
        Symbol tanh1 = Activation("tanh1", conv1, ActivationActType::sigmoid);
        Symbol pool1 = Pooling("pool1", tanh1, Shape(2, 2),
            PoolingPoolType::avg, Shape(2, 2));
        Symbol flatten = Flatten("flatten", pool1);
        Symbol fc1 = FullyConnected("fc1", flatten, fc1_w, fc1_b, 2);
        Symbol tanh2 = Activation("tanh2", fc1, ActivationActType::sigmoid);
        Symbol fc2 = FullyConnected("fc2", tanh2, fc2_w, fc2_b, 2);

**Comment by zhubuntu** [comment]
@luoruisichuan R语言的资料没有，参数说明我是根据[link](http://github.com/dmlc/MXNet.cpp/blob/master/include/mxnet-cpp/op.h)
看的

**Comment by luoruisichuan** [comment]
谢谢。
感觉MXNET的R语句比较简洁,但就是没有相关参数语句API DOCUMNET不太方便，谢谢了！

**Comment by luoruisichuan** [comment]
关于图像数据的输入，有如下帮助资料，
Create Dataset Using RecordIO
RecordIO implements a file format for a sequence of records. We recommend storing images as records and pack them together. The benefits are:
Storing images in compacted format, e.g. JPEG, for records can have different size. Compacted format will greatly reduce the dataset size in disk.
Packing data together allow continous reading on the disk.
RecordIO has a simple way of partition, which makes it easier for distributed setting. Example about this will be provided later.
We provide the “im2rec tool” to create Image RecordIO dataset by yourself. Here’s the walkthrough:
0.Before you start
Make sure you have downloaded the data. You don’t need to resize the images by yourself, currently im2rec could resize it automatically. You could check the promoting message of im2rec for details.
1.Make the image list
After you get the data, you need to make a image list file first. The format is
integer_image_index \t label_index \t path_to_image
In general, the program will take a list of names of all image, shuffle them, then separate them into training files name list and testing file name list. Write down the list in the format.
A sample file is provided here
895099  464     n04467665_17283.JPEG
10025081        412     ILSVRC2010_val_00025082.JPEG
74181   789     n01915811_2739.JPEG
10035553        859     ILSVRC2010_val_00035554.JPEG
10048727        929     ILSVRC2010_val_00048728.JPEG
94028   924     n01980166_4956.JPEG
1080682 650     n11807979_571.JPEG
972457  633     n07723039_1627.JPEG
7534    11      n01630670_4486.JPEG
1191261 249     n12407079_5106.JPEG

请问，有“im2rec tool” 方面的使用介绍吗？谢谢

**Comment by zhubuntu** [comment]
@luoruisichuan 没有，这里有一个MXnet交流群，你可以去问一下103907192

**Comment by luoruisichuan** [comment]
谢谢
